services:
  caddy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: caddy
    restart: unless-stopped
    env_file:
      - .env
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
      - DOMAIN=${DOMAIN}
      - BACKEND_URL=${BACKEND_URL}

volumes:
  caddy_data:
  caddy_config:
